# Generated by Django 2.1.7 on 2019-02-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('text', models.TextField(null=True, blank=True)),
                ('author', models.CharField(max_length=100, null=True, blank=True)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.CharField(max_length=50)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('explanation', models.TextField(null=True, blank=True)),
                ('publish_date', models.DateField(null=True, blank=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
