# Generated by Django 2.1.7 on 2019-03-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=50)),
                ('domain', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('articles', models.ManyToManyField(blank=True, related_name='decks', to='articles.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.Tag'),
        ),
    ]
