# Generated by Django 2.1.7 on 2019-04-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
