# Generated by Django 2.1.7 on 2019-04-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190416_1414'),
        ('articles', '0002_auto_20190416_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='false_swipers',
            field=models.ManyToManyField(related_name='false_swiped', to='accounts.Player'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_poll',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='true_swipers',
            field=models.ManyToManyField(related_name='true_swiped', to='accounts.Player'),
        ),
        migrations.AlterField(
            model_name='article',
            name='truth_value',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
