# Generated by Django 2.1.7 on 2019-04-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190404_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='truth_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
