# Generated by Django 2.1.7 on 2019-04-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190419_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='thumbnail_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
