# Generated by Django 2.1.7 on 2019-04-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190405_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='articles.Tag'),
        ),
    ]
