# Generated by Django 2.1.7 on 2019-04-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190406_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='truth_value',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
