# Generated by Django 2.1.7 on 2019-04-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_url_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100, unique=True)),
                ('credibility', models.PositiveSmallIntegerField(blank=True, default=5)),
                ('is_satire', models.BooleanField(blank=True, default=False)),
                ('rating', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
