# Generated by Django 2.1.7 on 2019-04-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='url_hash',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
