# Generated by Django 2.1.7 on 2019-04-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190406_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='subject',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
