# Generated by Django 2.1.7 on 2019-04-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190407_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='tags',
            field=models.ManyToManyField(blank=True, editable=False, related_name='tags', to='articles.Tag'),
        ),
    ]
