# Generated by Django 2.1.7 on 2019-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190420_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaintag',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
