# Generated by Django 2.1.7 on 2019-04-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20190420_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='is_satire',
        ),
    ]
