# Generated by Django 2.1.7 on 2019-04-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_domain_is_satire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='thumbnail_url',
            field=models.ImageField(blank=True, null=True, upload_to='deck_thumbnails'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='thumbnail_url',
            field=models.ImageField(blank=True, null=True, upload_to='tag_thumbnails'),
        ),
    ]
