# Generated by Django 2.1.7 on 2019-04-14 15:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('player_pks', models.CharField(default='', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message=None)])),
                ('scores', models.CharField(default='', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message=None)])),
                ('deck', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Deck')),
                ('players', models.ManyToManyField(related_name='games', to='accounts.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_players', models.IntegerField(default=2, editable=False)),
                ('status', models.CharField(blank=True, default='NEW', editable=False, max_length=128)),
                ('subject', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('article_counter', models.IntegerField(default=0)),
                ('deck', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.Deck')),
            ],
        ),
    ]
