# Generated by Django 2.1.7 on 2019-04-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='subject',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
