# Generated by Django 2.1.7 on 2019-04-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_players',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
