# Generated by Django 2.1.7 on 2019-03-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20190324_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_players',
            field=models.IntegerField(default=4, editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(default='NEW', editable=False, max_length=128),
        ),
    ]
