# Generated by Django 2.1.7 on 2019-04-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20190413_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_players',
            field=models.IntegerField(default=2, editable=False),
        ),
    ]
