# Generated by Django 2.1.7 on 2019-04-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20190421_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='waiting',
            field=models.BooleanField(default=True),
        ),
    ]
