# Generated by Django 2.1.7 on 2019-04-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20190412_0846'),
        ('accounts', '0010_auto_20190412_0755'),
        ('rooms', '0003_auto_20190412_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(editable=False)),
                ('deck', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Deck')),
                ('player', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='accounts.Player')),
            ],
        ),
    ]
