# Generated by Django 2.1.7 on 2019-04-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_waiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='waiting',
        ),
        migrations.AddField(
            model_name='room',
            name='players_waiting',
            field=models.IntegerField(default=0),
        ),
    ]
