# Generated by Django 2.1.7 on 2019-04-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190412_0939'),
        ('articles', '0009_auto_20190412_0846'),
        ('rooms', '0005_auto_20190412_0949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameResults',
            new_name='GameResult',
        ),
    ]
