# Generated by Django 2.1.7 on 2019-04-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20190412_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
