# Generated by Django 2.1.7 on 2019-04-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_gameresult_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='game_uid',
            field=models.UUIDField(null=True),
        ),
    ]
