# Generated by Django 2.1.7 on 2019-04-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20190413_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='article_counter',
            field=models.IntegerField(default=0),
        ),
    ]
