# Generated by Django 2.1.7 on 2019-04-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20190413_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tag',
        ),
    ]
