# Generated by Django 2.1.7 on 2019-04-14 11:02

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190413_1800'),
        ('rooms', '0010_remove_room_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='game_uid',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='player',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='score',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='player_pks',
            field=models.CharField(default='', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='players',
            field=models.ManyToManyField(related_name='games', to='accounts.Player'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='scores',
            field=models.CharField(default='', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
