# Generated by Django 2.1.7 on 2019-03-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190324_1213'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complete',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(null=True, related_name='interested_users', to='articles.Tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('X', 'Unknown'), ('KG', 'Kindergarten'), ('PR', 'Primary'), ('SE', 'Secondary'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PH', 'Doctorate')], default='SE', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='players', to='rooms.Room'),
        ),
    ]
