# Generated by Django 2.1.7 on 2019-04-01 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('rooms', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('score', models.IntegerField(default=0, editable=False)),
                ('hosted_room', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host', to='rooms.Room')),
                ('room', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='players', to='rooms.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('education', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Kindergarten'), (2, 'Primary'), (3, 'Secondary'), (4, 'Undergraduate'), (5, 'Postgraduate'), (6, 'Doctorate')], default=0)),
                ('interests', models.ManyToManyField(related_name='interested_users', to='articles.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hosted_room',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='room',
        ),
    ]
