# Generated by Django 2.1.7 on 2019-04-04 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190404_0802'),
        ('accounts', '0002_auto_20190401_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skill_rating',
            field=models.IntegerField(default=500, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'Prefer not to say')], default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='starred_decks',
            field=models.ManyToManyField(related_name='starrers', to='articles.Deck'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'Kindergarten'), (2, 'Primary'), (3, 'Secondary'), (4, 'Undergraduate'), (5, 'Postgraduate'), (6, 'Doctorate')], default=0),
        ),
    ]
