# Generated by Django 2.1.7 on 2019-04-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190404_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
    ]
