# Generated by Django 2.1.7 on 2019-04-21 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_player_game_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='skill_rating',
            field=models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
