# Generated by Django 2.1.7 on 2019-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190405_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='articles.Tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='starred_decks',
            field=models.ManyToManyField(blank=True, related_name='starrers', to='articles.Deck'),
        ),
    ]
