# Generated by Django 2.1.7 on 2019-04-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190407_1256'),
        ('accounts', '0008_auto_20190406_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='finished_decks',
            field=models.ManyToManyField(blank=True, related_name='finishers', to='articles.Deck'),
        ),
    ]
