# Generated by Django 2.1.7 on 2019-04-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_finished_decks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='players', to='rooms.Room'),
        ),
    ]
