# Generated by Django 2.1.7 on 2019-04-13 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20190412_0846'),
        ('accounts', '0012_auto_20190412_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='finished_decks',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='starred_decks',
        ),
        migrations.AddField(
            model_name='player',
            name='finished_decks',
            field=models.ManyToManyField(blank=True, editable=False, related_name='finishers', to='articles.Deck'),
        ),
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='starred_decks',
            field=models.ManyToManyField(blank=True, related_name='starrers', to='articles.Deck'),
        ),
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='rooms.Room'),
        ),
    ]
