# Generated by Django 2.1.7 on 2019-04-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoardStaleMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DurationField(null=True, unique=True)),
                ('fresh', models.BooleanField(default=False)),
            ],
        ),
    ]
